### PR TITLE
Switch to dmalloc() for low memory devices

### PR DESCRIPTION
**Pull request by diepquynh**
By default, Android uses jemalloc() for ART, which is "slightly" optimized for multi-core devices
Our device is single-core, so it can handle single-threaded operations only. As in case, swappings is one example. If you're playing such games as "Asphalt 8", you can experience "LAGS EVERYWHERE" and in worst case, FC happens, even you still have lots of RAM
Here's the user (or a dev)'s experience about this: http://forum.xda-developers.com/showpost.php?p=62476868&postcount=3492

### CODE REVIEW

**Comment by ngoquang2708** [comment]
If you don't mind, please close this PR, revert commit 6cda47ec739f4391570ff01ddd7d13b06039e2c3. Or I just close this PR and cherry-pick commit bf237ec609f2f91c72deeae78ac8c173ad1cffc0.

**Comment by diepquynh** [comment]
Oh shit, forgot to revert it

**Comment by ngoquang2708** [comment]
No need to close this, just revert that commit, it will append to this PR too.

**Comment by diepquynh** [comment]
Umm... OK

**Comment by diepquynh** [comment]
Can you cherry-pick my commit?
The internet is damn laggy at this time, i can't even pull the source down (12kbps)

**Comment by diepquynh** [comment]
OK, it's fine now :D
Reverted

**Pull request merged**
